### ISSUE TITLE
Visiting a path doesn't work on selenium or chrome

### ISSUE THREAD

**Issue by cihad** [jnicklas/capybara#1495]
`spec/rails_helper.rb`:

~~~ruby
# ... 
require 'capybara/rails'
require 'capybara/rspec'
Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end
# ...
~~~

my login method:
~~~ruby
  def login user = create(:authenticated)
    visit "users/login"
    within "form#new_user" do
      fill_in "user_email", with: user.email
      fill_in "user_password", with: user.password
      click_on I18n.t('sessions.login')
    end
  end
~~~

`spec/features/content_spec.rb`:

~~~ruby
require "rails_helper"

feature "Content" do
  
  let(:user) { create :authenticated }

  before do
    login user
  end

  scenario "User creates a new content", driver: :chrome do
    visit "nodes/new/content"
    click_link "New content"

    fill_in "content_title", with: "Example Title"
    fill_in "content_body", with: "Example Body"

    click_on "Submit"

    expect(page).to have_content "Example Title"
    expect(page).to have_content "Example Body"

  end

end
~~~

I got this error:
~~~
F

Failures:

  1) Content User creates a new content
     Failure/Error: login user
     Selenium::WebDriver::Error::UnknownError:
       unknown error: unhandled inspector error: {"code":-32603,"message":"Cannot navigate to invalid URL"}
         (Session info: chrome=41.0.2272.101)
         (Driver info: chromedriver=2.9.248316,platform=Linux 3.16.0-33-generic x86)
     # ./spec/support/helpers/test_helpers.rb:11:in `login'
     # ./spec/features/content_spec.rb:8:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 2.23 seconds (files took 0.36191 seconds to load)
1 example, 1 failure

~~~

When i am using `:selenium` driver:

~~~
F

Failures:

  1) Content User creates a new content
     Failure/Error: login user
     Selenium::WebDriver::Error::UnknownError:
       f.QueryInterface is not a function
     # [remote server] file:///tmp/webdriver-profile20150331-7206-1fder92/extensions/fxdriver@googlecode.com/components/driver-component.js:10132:in `FirefoxDriver.prototype.get'
     # [remote server] file:///tmp/webdriver-profile20150331-7206-1fder92/extensions/fxdriver@googlecode.com/components/command-processor.js:12274:in `DelayedCommand.prototype.executeInternal_/h'
     # [remote server] file:///tmp/webdriver-profile20150331-7206-1fder92/extensions/fxdriver@googlecode.com/components/command-processor.js:12279:in `DelayedCommand.prototype.executeInternal_'
     # [remote server] file:///tmp/webdriver-profile20150331-7206-1fder92/extensions/fxdriver@googlecode.com/components/command-processor.js:12221:in `DelayedCommand.prototype.execute/<'
     # ./spec/support/helpers/test_helpers.rb:11:in `login'
     # ./spec/features/content_spec.rb:8:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 5.46 seconds (files took 0.35364 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/content_spec.rb:11 # Content User creates a new content

~~~

How can i fix this problem?

**Comment by alexanderadam** [comment]
@cihad how did you fix it?

**Comment by twalpole** [comment]
@alexanderadam Most likely updating chrome and/or chromedriver

**Comment by alexanderadam** [comment]
@twalpole I ran just yesterday into this issue with latest chrome, chromedriver and capybara.
I changed a lot on the configuration though and it doesn't happen anymore. But it seems to be still appearing on current libraries.

**Comment by twalpole** [comment]
@alexanderadam In the future, rather than tacking onto an issue closed 3 years ago, please file a new issue with a way to reproduce and we will look into it.  Any solution to an issue over a year ago really isn't going to be relevant anymore.
