### ISSUE TITLE
Use `within()` on a table's tbody to select checkboxes

### ISSUE THREAD

**Issue by onebree** [jnicklas/capybara#1496]
**Rails 4.2.0, RSpec 3.1, Capybara 2.4.4, Capybara Webkit 1.3.1**

My `checkbox` method finds a checkbox based on its HTML element value. My tests are failing with the following Nokigiri error, but I figured asking for help here, since I am using Capybara to select the elements.

```
  1) Exercise the AMI Users Page PERMISSIONS disable ami user
     Failure/Error: within("#ami_users tbody") { checkbox(@ext_user2.id).set(false) }
     Nokogiri::CSS::SyntaxError:
       unexpected '=' after '#<Nokogiri::CSS::Node:0x00000007ede480>'
     # (eval):3:in `_racc_do_parse_c'
     # (eval):3:in `do_parse'
     # ./spec/support/helper.rb:53:in `checkbox'
     # ./spec/features/admin/ami_users_spec.rb:119:in `block (4 levels) in <top (required)>'
     # ./spec/features/admin/ami_users_spec.rb:119:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'
```

**Comment by twalpole** [comment]
Please ask how to questions on the mailing list as requested in the README
