### ISSUE TITLE
Mysql2 Threading Error during Capybara Javascript testing.

### ISSUE THREAD

**Issue by reidcooper** [jnicklas/capybara#1598]
I am currently trying to run a rspec test with Capybara and Database cleaner and I repetitively receive this threading error with Mysql.

Gemfile.lock

rspec (3.3.0)
capybara (2.4.4)
capybara-webkit (1.4.1)
database_cleaner (1.5.1)

````
Failure/Error: Unable to find matching line from backtrace
     ActiveRecord::StatementInvalid:
       Mysql2::Error: This connection is in use by: #<Thread:0x007f9fa58b9f88 sleep>: BEGIN
     # /Users/reidcooper/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
     # /Users/reidcooper/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
````

spec_helper.rb
````
  config.use_transactional_fixtures = false

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :truncation
  end

  config.before(:each, :js => true) do
    DatabaseCleaner.strategy = :truncation
  end

  config.before(:each, :feature => true) do
    DatabaseCleaner.strategy = :truncation
  end

  config.before(:each) do
    Warden.test_mode!
    DatabaseCleaner.start
  end

  config.after(:each) do
    Spree::User.auditing_enabled = false # if we don't disable auditing we run into a StackLevelTooDeep
    DatabaseCleaner.clean
    Warden.test_reset!
  end

  config.around(:each) do |example|
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.cleaning do
      example.run
    end
  end
````

The Spec File

````
    it "should let me navigate to the registration page", :js => true do
      visit '/products/tshirt'
      save_and_open_screenshot
      expect(page.status_code).to eq(200)
      expect(page).to have_content "CONTENT"
    end
````

Now the webpage screenshot shows up correct, however, I feel like its something to do with the javascript causing a threading issue.

**Comment by twalpole** [comment]
You're sharing the database connection between the test and server threads and/or you have AJAX requests still occurring when database cleaner is trying to truncate the database - either way this should be asked on the mailing list as requested in the README
