### ISSUE TITLE
expected not to find xpath "/html/body/*", found 3 matches:

### ISSUE THREAD

**Issue by chalmagean** [jnicklas/capybara#1645]
Hey guys, I'm getting this exception and I can't figure out why.

```
      expected not to find xpath "/html/body/*", found 3 matches: "", "Log in Welcome back Sign up Join the community myproj.com Community curated directory of 0 EVENTS", "". Also found "", which matched the selector but not all filters. (Capybara::ExpectationNotMet)
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara/node/matchers.rb:125:in `block in assert_no_selector'
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara/node/base.rb:84:in `synchronize'
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara/node/matchers.rb:121:in `assert_no_selector'
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara/session.rb:109:in `reset!'
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara.rb:285:in `block in reset_sessions!'
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara.rb:285:in `each'
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara.rb:285:in `reset_sessions!'
      ~/.rvm/gems/ruby-2.2.4@myproj/gems/capybara-2.6.2/lib/capybara/cucumber.rb:8:in `After'
```

**Comment by adsteel** [comment]
@chalmagean You'll have more luck with questions on either the mailing list or stackoverflow.

**Comment by twalpole** [comment]
Closing since this is a question and not an issue - please read the top of the README
