### ISSUE TITLE
error occurs when you save ActiveRecord models - exception":["SystemStackError","stack level too deep"]

### ISSUE THREAD

**Issue by danilvoe** [jnicklas/capybara#1689]
error -
 ```
ExternalIssue Store (28.3ms)  {"id":405393,"exception":["SystemStackError","stack level too deep"]}
SystemStackError: stack level too deep
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
... 4498 levels...
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/voe/portaltp/portaltp/bin/rails:8:in `<top (required)>'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/voe/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /home/voe/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/voe/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from exit
```

debugging result -

```

[69, 78] in /home/voe/portaltp/portaltp/srcipts_manual/DownloadIssueEGRON.rb
   69:         @file.puts("Сбой парсинга или записи в БД. Обращение " + numberRawNumberIssue.to_s + " " + e.to_s)
   70:         @file.puts("Сбой парсинга или записи в БД. Обращение " + numberRawNumberIssue.to_s + " " + e.backtrace.to_s)
   71:         e.class.to_s
   72:         raise ActiveRecord::Rollback
   73:     end
=> 74:   end
   75: end
   76: 
   77: ######################################################################################################################################
   78: ############## 
(byebug) next

[184, 193] in /home/voe/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb
   184:         yield
   185:       rescue Exception => error
   186:         rollback_transaction if transaction
   187:         raise
   188:       ensure
=> 189:         unless error
   190:           if Thread.current.status == 'aborting'
   191:             rollback_transaction if transaction
   192:           else
   193:             begin
(byebug) next

[185, 194] in /home/voe/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb
   185:       rescue Exception => error
   186:         rollback_transaction if transaction
   187:         raise
   188:       ensure
   189:         unless error
=> 190:           if Thread.current.status == 'aborting'
   191:             rollback_transaction if transaction
   192:           else
   193:             begin
   194:               commit_transaction
(byebug) next

[188, 197] in /home/voe/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb
   188:       ensure
   189:         unless error
   190:           if Thread.current.status == 'aborting'
   191:             rollback_transaction if transaction
   192:           else
=> 193:             begin
   194:               commit_transaction
   195:             rescue Exception
   196:               transaction.rollback unless transaction.state.completed?
   197:               raise
(byebug) next

[189, 198] in /home/voe/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb
   189:         unless error
   190:           if Thread.current.status == 'aborting'
   191:             rollback_transaction if transaction
   192:           else
   193:             begin
=> 194:               commit_transaction
   195:             rescue Exception
   196:               transaction.rollback unless transaction.state.completed?
   197:               raise
   198:             end
(byebug) next
   (3.6ms)  COMMIT

```

then the console crashes without an error

**Comment by danilvoe** [comment]
setting

Capybara.configure do |config|
  config.javascript_driver = :webkit
  config.current_driver = :webkit
  config.run_server = false
end
Capybara::Webkit.configure do |config|
  config.allow_unknown_urls
  config.skip_image_loading
end

**Comment by danilvoe** [comment]
the problem occurs when you use gem searchkisk when performing indexing

**Comment by danilvoe** [comment]
problem only occurs if you are using  - Capybara::DSL

**Comment by twalpole** [comment]
Somehow you've created an endless loop between two methods - this could occur if Capybara and Searchkick are included into the same object and have some methods named identically.  That being said there is no reason for those two gems to be included into the same model, so my guess is you're doing something wrong, like including Capybara::DSL into Object?

**Comment by danilvoe** [comment]
For yet need both gem. I gave up mixing Capybara :: DSL, and the problem has disappeared, if it is possible to make so that the mixing does not interfere with searchkisk would be great if you can not make it possible to close the issue.

**Comment by twalpole** [comment]
I don't understand what you're asking - what class are you including Capybara::DSL into?

**Comment by twalpole** [comment]
Closing due to lack of response, we can reopen if/when more info is provided
